version: '3.6'

x-shared-environment: &commonEnv
    POSTGRES_USER: "postgres"
    POSTGRES_PASSWORD: "postgres"
    POSTGRES_PORT: 5432
    POSTGRES_HOST: "rdbms_vales"
    POSTGRES_DB: "vales_dylk"

services:
    neon_nights:
        container_name: 'neon_nights'
        build: './DOS/api-vales'
        ports:
          - '10080:10080'
        environment: *commonEnv
        networks:
          - operational_network
    rdbms_vales:
        container_name: 'rdbms_vales'
        image: 'debezium/postgres'
        ports:
          - '5432:5432'
        environment: *commonEnv
        volumes:
          - serv_vales_pg_data:/var/lib/postgresql/data
        networks:
          - operational_network


networks:
    operational_network:
        name: operational_network
        driver: bridge


volumes:
    serv_vales_pg_data:
